X-Zalando-Team: tip
X-Zalando-Type: tools

approvals:
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      - zalando
      - zalando-incubator
    # OR a collaborator of the repo
    collaborators: true
